export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const FETCH_SKILLS_REQUEST = "FETCH_SKILLS_REQUEST";
export const FETCH_SKILLS_SUCCESS = "FETCH_SKILLS_SUCCESS";
export const FETCH_SKILLS_FAILED  = "FETCH_SKILLS_REQUEST";
